### ISSUE TITLE
Actualizar index con nuevas páginas.

### ISSUE THREAD

**Issue by TomFisso** [silvana85/igsoft#31]

**Comment by silvana85** [comment]
@TomFisso A qué se refiere el título?

**Comment by TomFisso** [comment]
> @TomFisso A qué se refiere el título?

Sil me lo cree para no olvidarme de que cada vez que creábamos una página la tenía que agregar en el index.html ( es donde están listadas todas las páginas )

**Comment by silvana85** [comment]
> > @TomFisso ¿ A qué se refiere el título?
> 
> Sil me lo cree para no olvidarme de que cada vez que creábamos una página la tenía que agregar en el index.html (es donde están listadas todas las páginas)

Excelente Tomy! Gracias!
